// Widget: Geometrie
WIDGETS.push({
  meta: { type:"geometry", label:"Geometrie", desc:"Formen & Maße", icon:"◻", category:"mathematik" },
  createData: id => ({ id, type:"geometry", shape:"rectangle", label:"Berechne den Flächeninhalt.", a:6, b:4 , aufgabenNr:0, aufgabenText:''}),
  render: d => {
    const {shape,a,b,label}=d; let svg="";
    if(shape==="rectangle"){const w=Math.min(a*18,160),h=Math.min(b*18,110);svg=`<svg width="${w+60}" height="${h+40}" style="overflow:visible;"><rect x="30" y="10" width="${w}" height="${h}" fill="#e8f4fd" stroke="#89b4fa" stroke-width="2" rx="2"/><text x="${30+w/2}" y="${h+28}" text-anchor="middle" font-size="12" fill="#555">${a} cm</text><text x="14" y="${10+h/2}" text-anchor="middle" font-size="12" fill="#555" transform="rotate(-90,14,${10+h/2})">${b} cm</text></svg>`;}
    else if(shape==="triangle"){const bw=Math.min(a*20,160),h2=Math.min(b*16,100),cx=30+bw/2;svg=`<svg width="${bw+60}" height="${h2+40}" style="overflow:visible;"><polygon points="${cx},10 ${30},${10+h2} ${30+bw},${10+h2}" fill="#fef3e2" stroke="#fab387" stroke-width="2"/><text x="${cx}" y="${10+h2+22}" text-anchor="middle" font-size="12" fill="#555">${a} cm</text><text x="${30+bw+8}" y="${10+h2/2}" font-size="12" fill="#555">${b} cm</text></svg>`;}
    else if(shape==="circle"){const r=Math.min(a*9,70);svg=`<svg width="${r*2+40}" height="${r*2+30}" style="overflow:visible;"><circle cx="${r+20}" cy="${r+10}" r="${r}" fill="#f0fdf4" stroke="#a6e3a1" stroke-width="2"/><line x1="${r+20}" y1="${r+10}" x2="${r*2+20}" y2="${r+10}" stroke="#555" stroke-width="1.5" stroke-dasharray="4,2"/><text x="${r+20+r/2}" y="${r+6}" text-anchor="middle" font-size="12" fill="#555">r = ${a} cm</text></svg>`;}
    return atHtml(d) + `<div>${label?`<div style="font-size:13px;color:#555;margin-bottom:10px;">${esc(label)}</div>`:""}<div style="margin:8px 0;">${svg}</div><div style="display:flex;gap:5px;align-items:center;font-size:13px;margin-top:8px;"><span>Flächeninhalt:</span><div style="border-bottom:1.5px solid #999;flex:1;height:20px;max-width:120px;"></div><span>cm²</span></div></div>`;
  },
  renderProps: d => atProps(d.id, d) + pr("Form",`<select onchange="upd(${d.id},'shape',this.value)"><option value="rectangle" ${d.shape==="rectangle"?"selected":""}>Rechteck</option><option value="triangle" ${d.shape==="triangle"?"selected":""}>Dreieck</option><option value="circle" ${d.shape==="circle"?"selected":""}>Kreis</option></select>`)+pr(d.shape==="circle"?"Radius (cm)":"Seite a (cm)",`<input type="number" min="1" max="15" value="${d.a}" onchange="upd(${d.id},'a',+this.value)">`)+( d.shape!=="circle"?pr("Seite b (cm)",`<input type="number" min="1" max="15" value="${d.b}" onchange="upd(${d.id},'b',+this.value)">`):"")+pr("Aufgabentext",`<input value="${esc(d.label)}" onchange="upd(${d.id},'label',this.value)">`),
});
